### ISSUE TITLE
SATA to dSATA Staking Pool

### ISSUE THREAD

**Issue by cl-tim** [congruentlabs/signata-dao#2]
_The token allocation to be made:_

5,000,000.00 dSATA

_The purpose of the allocation, and a justification as to requiring the modification to be made:_

24,000,000+ dSATA are expected to remain in circulation after the migration period ends. To provide an opportunity for SATA holders to earn governance tokens, a pool for staking Ethereum SATA to earn dSATA is proposed to be created.

Proposed parameters for the pool:

- Pool ends 2022-11-30 (6 months)
- 7 day minimum staking time
- 3.8954 dSATA earned per block across all users in the pool
- The pool will be established on the OKLG token farming service. Yield is not static. More SATA entering the pool will lower the yield for all stakers (as well as the inverse being true).

**Comment by cl-tim** [comment]
The dSATA contract will not collect fees for moving dSATA in or out of any staking pool

**Comment by SataCenturion** [comment]
I am not against the proposal, but just want to voice my concern that it is possible for a large number of dSata to be accumulated by whales and have a large amount of control over the direction of the DAO. 

Hopefully this staking pool allows a larger distribution of governance tokens across our holder base.

**Comment by RobbyBobson** [comment]
I support this proposal, and think that it could be implemented just as Tim has suggested. 
SataCenturion is right to a degree, but I'm not sure how we could combat that with the pool parameters. If anything, right now dSATA is already able to be 'manipulated' by whales as there are so few holders. Perhaps this pool will encourage others to get on board and the token's distribution will improve?

**Comment by SATAvocado** [comment]
I voice a similar concern regarding low participation leading to large accumulation. The current block reward of 3.8954 dSATA will give approximately 25,000 per day to be split by participants. I'm not totally against the pool, but it might need some adjustments to block reward or total allocation.

**Comment by BIGDOGGYSTYLER** [comment]
As much as I support this proposal, I believe it neglects SATA LP providers. If there is a way to include their wallet addresses into this pool, I would back it 100%

**Comment by RobbyBobson** [comment]
What are the suggestions then so that we can go ahead and vote on this? 
We need to get this moving.

**Comment by cl-tim** [comment]
> As much as I support this proposal, I believe it neglects SATA LP providers. If there is a way to include their wallet addresses into this pool, I would back it 100%

That's what the other open proposal is for, for SATA LP providers. The pool can't be a combination of the two as the base staked tokens are entirely different with different price mechanisms.

But a 2nd dSATA yielding pool could be created for SATA LP providers? If you're wanting something like that a proposal can be opened for that too.

**Comment by cl-tim** [comment]
> I voice a similar concern regarding low participation leading to large accumulation. The current block reward of 3.8954 dSATA will give approximately 25,000 per day to be split by participants. I'm not totally against the pool, but it might need some adjustments to block reward or total allocation.

There's 2 ways to change the distribution. Either extend the pool to a longer timespan, or reduce the pool reward supply.

Would you all prefer a 1 year pool with the same amount? Or the 5,000,000 dSATA reduced to something like 3,000,000? Up to you guys

**Comment by BIGDOGGYSTYLER** [comment]
In favour of changing the parameters to 1 year

**Comment by RunningWithTurtles** [comment]
In favor of extending to 1 year while keeping the reward at 5,000,000.

**Comment by RobbyBobson** [comment]
I also am in favour. Who's gonna get this proposal on Tally?

**Comment by cl-tim** [comment]
1 year it is. Nobody has voiced any objections. I'll open the proposal now

**Comment by cl-tim** [comment]
Proposal opened:

https://www.tally.xyz/governance/eip155:1:0x3D3255D21654B9a8325DfE6353ac6B37352Eb80B/proposal/112193124163354052763328533223595436589147810764624453813670041301179215386123

**Comment by cl-tim** [comment]
Proposal #2 has been executed. As per community vote, staking to receive governance tokens is now active on OKLG

https://app.oklg.io/#/faas

https://etherscan.io/tx/0xc5c9e5a910a1862a6a73e1a400b9ab630d6c87146d76d374d8273e096510e857
