### ISSUE TITLE
SATA Development Bounty Pool

### ISSUE THREAD

**Issue by cl-tim** [congruentlabs/signata-dao#4]
_The token allocation to be made:_

100,000.00 SATA

_The purpose of the allocation, and a justification as to requiring the modification to be made:_

To establish a developer bounty fund for the project. External developers need to be encouraged to contribute to the project to increase decentralization.

SATA tokens to be held by the project DAO Custodian at: 0x0B21eF0d5430009C21945218d69E3F92c9cf8Dbc

Individual contribution bounty amounts will be determined as they're created. Each GitHub issue for the source code projects (not this DAO management project) will include a bounty amount determined at an estimate of the hours needed for development and the value of the SATA tokens at the time. Contributions that are accepted and merged will then pay the bounty out to the contributor if they provide a wallet address.

If the fund is not consumed within 12 months it will be returned to the treasury.

**Comment by RobbyBobson** [comment]
Sounds great. I'm voting in favor.

**Comment by RandySavageCreamOCrop** [comment]
I support this. Will the specific bounty amounts also be put up for vote?

**Comment by cl-tim** [comment]
> I support this. Will the specific bounty amounts also be put up for vote?

I don't think people will want to have to vote on each individual piece of work that has a bounty on it, especially because the value of the bounty could change in the time of undertaking the vote and we will hopefully end up with quite a lot of open bounties.

I was thinking we just put an estimate of the number of hours to do the pieces of work x the value of the tokens at the time. If nobody is willing, we adjust accordingly.

**Comment by BIGDOGGYSTYLER** [comment]
In favour.

Opening new bounties down the line would be ideal too.

**Comment by SataCenturion** [comment]
I'm in favour of this proposal. It's a no brainer to attract independent talent

**Comment by cl-tim** [comment]
No objections to this proposal have been raised. Opening for vote in 24 hours: https://www.tally.xyz/proposal/92a1506d-38a8-45f9-8609-a70ee07d5c6d

**Comment by cl-tim** [comment]
Proposal passed and executed now. Bounties will be opened as GitHub issues. https://www.tally.xyz/governance/eip155:1:0x3D3255D21654B9a8325DfE6353ac6B37352Eb80B/proposal/39375674010925166979315306862773323158659073126337436343140073268090591300411
