### ISSUE TITLE
[META] Modify Voting Period

### ISSUE THREAD

**Issue by cl-tim** [congruentlabs/signata-dao#5]
We likely have the voting period set too long, just based on the fact the first vote met quorum within 72 hours but it's 7 days long. And with the delay it's 8 days technically.

This is a proposal to modify the voting period to 72 hours (3 days).

This will still have the voting delay at 24 hours, so it's a 4 day vote cycle in total. The delay should always remain there because it allows people time to delegate if they haven't.

This vote WILL NOT use Tally. This is a "meta" vote (we're only modifying a parameter for voting), and as such we'll just use snapshot.org so we can set the vote for it as the same length of time that we're voting on.

We also want to ideally get this sorted before the other proposals go ahead, just so the community can have them sorted faster.

**Comment by RunningWithTurtles** [comment]
I agree with this and if it being only 4 days becomes an issue in the future, doubt it, it could be proposed to switch the amount of days again.

**Comment by SATAvocado** [comment]
I'm in favor!

**Comment by cl-tim** [comment]
> I agree with this and if it being only 4 days becomes an issue in the future, doubt it, it could be proposed to switch the amount of days again.

Exactly. If proposals are found to have holders not voting because they just miss them, we just vote to increase it. I'm sure there'll eventually be a percentage that won't participate no matter what, but if it's a large enough percentage that the outcome could be changed if they did participate, then it's worth adjusting.

**Comment by RobbyBobson** [comment]
Yeah definitely in favour.

**Comment by BIGDOGGYSTYLER** [comment]
In favour

**Comment by Satamarok** [comment]
Also in favour.

**Comment by cl-tim** [comment]
Opened on Snapshot. Voting will start at Jun 3, 2022, 12:00 PM

https://snapshot.org/#/sata.eth/proposal/0xa741526cbfa1ea3c9cfa7795a672985c7b585209af347b9ef7c5c1365574990a

**Comment by cl-tim** [comment]
Ok I'm a bit of a dumbarse and opened that Proposal #5 without actually verifying first if we could modify the voting period outside of a vote.

Turns out we can't. Extensions to the timelock contract were added for manual override by the contract owner, but those same extensions weren't added to the governor contract. It's ultimately a good thing as it means it must always be voted on, but my apologies for wasting people's time with the Snapshot.org vote - even though it passed we don't have the ability to change that voting period.

So a new Tally vote has been opened to get this sorted on-chain: https://www.tally.xyz/proposal/9d189a17-7e26-4f4f-95a0-ab397f41d45f


Signature:
setVotingPeriod(uint256)

Calldatas:
uint256: 19636

Target:
0x3D3255D21654B9a8325DfE6353ac6B37352Eb80B

Value:
0

**Comment by cl-tim** [comment]
Proposal passed! It's now pending queueing to the timelock. Can any proposal manager please jump on to Tally and queue the proposal so it can be executed (expand the "Manage Proposals" section on the DAO page): https://www.tally.xyz/governance/eip155:1:0x3D3255D21654B9a8325DfE6353ac6B37352Eb80B

**Comment by cl-tim** [comment]
Timelock executed. Voting Period now set to 19636 blocks

https://www.tally.xyz/governance/eip155:1:0x3D3255D21654B9a8325DfE6353ac6B37352Eb80B/proposal/88587712348383403159049089705188074973536447854843837529961097845766167893994
