### ISSUE TITLE
Governance - Adding NFT Rights for Governance

### ISSUE THREAD

**Issue by cl-tim** [congruentlabs/signata-dao#6]
Last year we had published an article discussion Non-Fungible Governance (NFG) for the project: https://blog.congruentlabs.co/non-fungible-governance/

As governance was tested against the SATA token it became apparent that it was not suitable and that a separate token would be required to meet the needs of a secure and actually decentralized governance layer for the project. The separate token being created in a completely different way of course meant most of the plans laid out in the NFG article no longer applied.

This proposal is to see if people want to introduce NFG for the dSATA governor contract.

### Implementation plan

Issue ERC721 Rights from the SATARIGHT contract https://etherscan.io/token/0x7c8890a02abd24ff00c4eb1425258ea4b611d300 representing:

- Partners & Liquidity Providers: voting multiplier of 2
- Early Holders & Standard Stakers: voting multiplier of 1.5
- Standard Holders: voting multiplier of 1.
- Project Custodians: excluded now as they must abstain from voting.

The original plans defined thresholds of circulating supply that would expire these rights. As these thresholds can potentially never be met, and stronger voting power from NFT holders may intentionally restrict supply releases to retain their voting power, it is proposed instead to put a 12 month expiry date that requires renewal by DAO vote. The DAO can also vote to cease the voting multipliers at any time.

This will require modification of the Governor contract to recognize these issued rights: https://github.com/congruentlabs/sata-contracts-v1/blob/main/contracts/Governor.sol

The new governor contract will replace the existing contract. The timelock contract will remain the same. Privileges will be migrated from the old governor contract to the new one to apply voting power to it.

### Proposal Outcomes

1. Vote FOR to have the custodian build the above extension to the governor contract with the voting multipliers included.
2. Vote AGAINST to not do any of the above and retain the existing governor contract.

**Comment by cl-tim** [comment]
An additional parameter needs to be decided on as well: if the NFT rights are transferrable (you can move them between wallets) or non-transferrable. If a the NFT is transferrable it will permit people to move them wherever they wish, including to a different holder that is not in the intended recipients. If it's non-transferrable then it is bound to the original wallet addresses as per the parameters above.

**Comment by nenenenene555** [comment]
I am FOR the proposal along with the right being non-transferrable.

**Comment by BIGDOGGYSTYLER** [comment]
I am FOR the proposal along with the rights being transferrable.

**Comment by SataCenturion** [comment]
I am for this proposal, along with having the rights be transferrable. 

I don't forsee a huge amount of rights being sold or traded but it adds a layer of convenience if you need to change wallets rather than have those rights lost forever. 

However I think that the quorum needs to be increased from it's current threshold if this passes, (or even if it doesn't) as a number of wallets are nearing the 2,000,000 requirement in their own right and we risk losing balance in the force.

**Comment by cl-tim** [comment]
It's 2v1 for transferrable, and nobody else has provided input. I'm pushing this to vote.

**Comment by cl-tim** [comment]
Proposal opened. As the outcome of the vote does not require treasury changes it can be handled on Snapshot:

https://snapshot.org/#/sata.eth/proposal/0xc9e2fc9506cb13928db8243c813814469b5c8e1d579d918acf4be682f68e346d

**Comment by cl-tim** [comment]
Vote passed. We have built this capability, we just need to conduct testing before release.
