### ISSUE TITLE
DAO Attack Attempt

### ISSUE THREAD

**Issue by cl-tim** [congruentlabs/signata-dao#8]
The following transaction has been identified as an attempt to attack the Signata DAO:

https://etherscan.io/tx/0xb8111eac7156f29b8e776d066bffb2dce7bde27719eaca31839458ec57a08b06#eventlog

The proposal is attempting to approve all SATA and dSATA tokens held by the treasury to the attackers address, letting them transfer the tokens out for unknown purposes.

The proposal data is as follows:

proposalId :
29219205494946647336622874446020237416401275630090653990734818546016248820543
proposer :
[0x0A8062Eb16956FF0E804f766ACD67d7bc4492d40](https://etherscan.io/address/0x0A8062Eb16956FF0E804f766ACD67d7bc4492d40)
targets :
0x3ebb4A4e91Ad83BE51F8d596533818b246F4bEe1
0x49428f057dd9d20a8E4c6873e98AFD8cD7146e3B
values :
0
0
signatures :

calldatas :
095EA7B30000000000000000000000000A8062EB16956FF0E804F766ACD67D7BC4492D40FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
095EA7B30000000000000000000000000A8062EB16956FF0E804F766ACD67D7BC4492D40FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
startBlock :
15730941
endBlock :
15750577
description :
# Modify Voting Period #5 https://github.com/congruentlabs/signata-dao/issues/5 This is a proposal to modify the voting period to 72 hours (3 days).

**Comment by cl-tim** [comment]
**Actions taken as custodian**

Proposer wallet blacklisted to prevent increasing voting power: https://etherscan.io/tx/0x33984b9ed30f6730ca4014ebaa695cdefa681d61222b1902d67830a31f8b26e9

Alert distributed to Telegram: https://t.me/signatanews/285

**Comment by cl-tim** [comment]
Both the vote failing to pass from sufficient "No" votes, and the intervention of proposal managers when the timelock period begins (immediately after the voting period ends) will ensure this proposal cannot pass.

**Comment by RunningWithTurtles** [comment]
Good catch 👍 

Does the vote even have to be pushed to a vote? Since it is a malicious proposal, can the managers agree to dismiss the proposal?

**Comment by cl-tim** [comment]
> Good catch 👍
> 
> Does the vote even have to be pushed to a vote? Since it is a malicious proposal, can the managers agree to dismiss the proposal?

It can't be cancelled if it meets the proposal threshold. It can only be cancelled by managers when the timelock period starts.

**Comment by GalSagie** [comment]
@cl-tim From my understanding it was alerted by "Cotrus2314" on your discord channel before you noticed it. (And explained in the channel as well before damage was done)
I think mentioning this and giving the credit  will help other protocols and DAO's to be better protected and trusting the relevant entity/company , would you agree? 
Maybe will be great to disclose all information for transparency

**Comment by cl-tim** [comment]
> @cl-tim From my understanding it was alerted by "Cotrus2314" on your discord channel before you noticed it. (And explained in the channel as well before damage was done)
> I think mentioning this and giving the credit  will help other protocols and DAO's to be better protected and trusting the relevant entity/company , would you agree? 
> Maybe will be great to disclose all information for transparency 

They were removed from Discord for violating the group rules. The DAO isn't here to promote other businesses or services.

**Comment by cl-tim** [comment]
Closing this, the vote failed
